variable "aws_region" {}
variable "vpc_cidr" {}
variable "subnet_cidr_1" {}
variable "subnet_cidr_2" {}
variable "subnet_cidr_3" {}
variable "az_1" {}
variable "az_2" {}
variable "az_3" {}
variable "ami_id" {}
variable "instance_type" {}
